apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: lm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: backend
          image: kix.ocir.io/axunckhvyv1v/lm-backend:latest
          ports:
            - containerPort: 8001
          envFrom:
            - secretRef:
                name: app-secrets
          # resources:
          #   requests:
          #     cpu: "500m"
          #     memory: "512Mi"
          #   limits:
          #     cpu: "1"
          #     memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: lm-app
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: lm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: frontend
          image: kix.ocir.io/axunckhvyv1v/lm-frontend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: lm-app
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: lm-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      imagePullSecrets:
        - name: ocir-secret
      containers:
        - name: auth
          image: kix.ocir.io/axunckhvyv1v/lm-auth:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: app-secrets
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASSWORD
          # resources:
          #   requests:
          #     cpu: "250m"
          #     memory: "256Mi"
          #   limits:
          #     cpu: "500m"
          #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: lm-app
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
