apiVersion: v1
kind: Secret
metadata:
  name: ocir-secret
  namespace: lm-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJraXgub2Npci5pbyI6eyJ1c2VybmFtZSI6ImF4dW5ja2h2eXYxdi9jb2RlbGFiIiwicGFzc3dvcmQiOiJde056e2VWLk41emxJVDAxdzFLaSJ9fX0=
# GitHub Actions에서 Secrets로 관리 필요
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: lm-app
type: Opaque
data:
  DATABASE_URL: {{ BASE64_ENCODED_DB_URL }}
  REDIS_PASSWORD: {{ BASE64_ENCODED_REDIS_PASSWORD }}