apiVersion: v1
kind: Namespace
metadata:
  name: lm-app
---
apiVersion: v1
kind: Secret
metadata:
  name: ocir-secret
  namespace: lm-app
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >-
    ${OCI_REGISTRY_AUTH_BASE64}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: lm-app
type: Opaque
data:
  DATABASE_URL: ${BASE64_ENCODED_DB_URL}
  REDIS_PASSWORD: ${BASE64_ENCODED_REDIS_PASSWORD}
