"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var multer_1 = require("multer");
var courseController_1 = require("../controllers/courseController");
var authMiddleware_1 = require("../middleware/authMiddleware");
var router = express_1.default.Router();
var upload = (0, multer_1.default)({ storage: multer_1.default.memoryStorage() });
router.get("/", courseController_1.listCourses);
router.post("/", authMiddleware_1.verifyToken, courseController_1.createCourse);
router.get("/:courseId", courseController_1.getCourse);
router.put("/:courseId", authMiddleware_1.verifyToken, upload.single("image"), courseController_1.updateCourse);
router.delete("/:courseId", authMiddleware_1.verifyToken, courseController_1.deleteCourse);
router.post("/:courseId/sections/:sectionId/chapters/:chapterId/get-upload-url", authMiddleware_1.verifyToken, courseController_1.getUploadVideoUrl);
exports.default = router;
